### ISSUE TITLE
Dark theme: darken the row separators

### ISSUE THREAD

**Issue by n0004082426262728** [Pusher-Labs/thorchain-explorer#121]
Love the dark theme except for the row separators, they're too white and create too much noise with the content. My eyes hurt when I look at it for too long. I'd prefer if on the dark theme the separators would be a darker shade to blend more with the table, while the text is light. I think it would pop better.

**Comment by n0004082426262728** [comment]
I'd do:

`border-bottom: 1px solid #232323;`

**Comment by stuartkuentzel** [comment]
yup, i agree, let's darken those borders in dark mode

**Comment by OleksandrHrybovoda** [comment]
I can do it

**Comment by stuartkuentzel** [comment]
updated 👍
