### ISSUE TITLE
Table data misaligned

### ISSUE THREAD

**Issue by n0004082426262728** [Pusher-Labs/thorchain-explorer#122]
In the Staker Pools table, the row data is misaligned from its headings: https://thorchain.net/stakers/bnb1puf4hvn73ffwsssag0l59erfv5m4d9vcxgnjdt

**Comment by n0004082426262728** [comment]
Actually just noticed a few tables have misalignment too :) https://thorchain.net/nodes

**Comment by HelloKashif** [comment]
Yes this one is tracked on a pending issue https://github.com/Pusher-Labs/thorchain-explorer/issues/85
Will be fixed next week.

**Comment by n0004082426262728** [comment]
Thanks sorry, I didn't look back.. should've had!
