### ISSUE TITLE
New Metric: How long did it take for the network to upgrade its version?

### ISSUE THREAD

**Issue by mehowbrains** [Pusher-Labs/thorchain-explorer#184]
It would be great to have a metric which shows the time it took for the network to upgrade to a new version.

We can already see how many nodes are running a new version, but it would be even-better to know how long the network took to perform the upgrade. This can instil confidence in the network as it shows responsiveness and care by operators.

I haven't looked at the MIDGARD API, but if it can show the latest version pushed and its timestamp, then it should be possible to do the work.

I'd be able to use such in marketing materials to show off the network's responsiveness.

**Comment by stuartkuentzel** [comment]
Midgard returns "current" and "next" version, no additional data. Right now we're just pulling from midgard, not aggregating anything or storing anything db side. This would be better to approach the Midgard dev team to implement, and then we could reflect their data.
