### ISSUE TITLE
Network - Total Pooled incorrect

### ISSUE THREAD

**Issue by kaiansaari** [Pusher-Labs/thorchain-explorer#197]
The total pooled stat from `/v1/network` `{totalStaked}` is multiplied by 2 incorrectly. Should not be multiplied as reflects both sides already.

https://github.com/Pusher-Labs/thorchain-explorer/blob/d1ddc9b8b86d3c20b3a8513d15ef92b04044e2de/src/app/_classes/network-status.ts#L107

**Comment by stuartkuentzel** [comment]
fixed in #199
