### ISSUE TITLE
Use Byzantine Module for network discovery

### ISSUE THREAD

**Issue by kaiansaari** [Pusher-Labs/thorchain-explorer#46]
**CMO:**

The `midgard` & `thornode` endpoints hard hard coded & will break if the thornode associated with the endpoint churns out.
https://github.com/Pusher-Labs/thorchain-explorer/blob/326cedf17383560b71286d04975bed397ed7dc35/src/environments/environment.prod.ts#L1-L5

https://github.com/Pusher-Labs/thorchain-explorer/blob/326cedf17383560b71286d04975bed397ed7dc35/src/environments/environment.ts#L5-L9

**FMO:**
Suggest using the `byzantine module` which will automatically discover the network and ensure a malicious node isn't serving bad data; and will select a node at random as the `baseUrl`.

https://gitlab.com/thorchain/byzantine-module

**Comment by stuartkuentzel** [comment]
A static node is used only for local development. On anything live, it hits 'https://a2wva4alb6.execute-api.us-east-1.amazonaws.com/dev/thornode', which is a lambda that uses the asgardex-midgard library and connects to a random node 👍
