### ISSUE TITLE
Constants Page with Mimir Overrides

### ISSUE THREAD

**Issue by stuartkuentzel** [Pusher-Labs/thorchain-explorer#64]
tables for constant types and values http://195.248.242.140:8080/v1/thorchain/constants (midgard endpoint)
if the value is overridden by mimir (http://195.248.242.140:1317/thorchain/mimir THORNode endpoint), show the mimir value as well.

**Comment by OleksandrHrybovoda** [comment]
I can do the task

**Comment by OleksandrHrybovoda** [comment]
check PR
