### ISSUE TITLE
Make table scrollable on mobile

### ISSUE THREAD

**Issue by rekt0x** [Pusher-Labs/thorchain-explorer#83]
On mobile the tables (e.g. at https://thorchain.net/nodes) can not be scrolled on mobile.

**Comment by stuartkuentzel** [comment]
Right now, on the nodes table for example, we use a "mobile-hidden" class to hide some of the columns. I think removing that class from tables and making them x-axis scrollable would be a nice improvement. The transactions table will need some extra love, as the css and mobile layout are a bit different than the rest of the tables.

**Comment by OleksandrHrybovoda** [comment]
Can do this task
